// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ResourceManifest.proto

package mps

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceManifest_StyleConfig_StyleID int32

const (
	ResourceManifest_StyleConfig__      ResourceManifest_StyleConfig_StyleID = 0
	ResourceManifest_StyleConfig_C3MM_1 ResourceManifest_StyleConfig_StyleID = 14
	ResourceManifest_StyleConfig_C3M    ResourceManifest_StyleConfig_StyleID = 15
	ResourceManifest_StyleConfig_DTM_1  ResourceManifest_StyleConfig_StyleID = 16
	ResourceManifest_StyleConfig_DTM_2  ResourceManifest_StyleConfig_StyleID = 17
	ResourceManifest_StyleConfig_C3MM_2 ResourceManifest_StyleConfig_StyleID = 52
)

var ResourceManifest_StyleConfig_StyleID_name = map[int32]string{
	0:  "_",
	14: "C3MM_1",
	15: "C3M",
	16: "DTM_1",
	17: "DTM_2",
	52: "C3MM_2",
}

var ResourceManifest_StyleConfig_StyleID_value = map[string]int32{
	"_":      0,
	"C3MM_1": 14,
	"C3M":    15,
	"DTM_1":  16,
	"DTM_2":  17,
	"C3MM_2": 52,
}

func (x ResourceManifest_StyleConfig_StyleID) String() string {
	return proto.EnumName(ResourceManifest_StyleConfig_StyleID_name, int32(x))
}

func (ResourceManifest_StyleConfig_StyleID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d561545c06fb5527, []int{0, 1, 0}
}

type ResourceManifest struct {
	StyleConfig          []*ResourceManifest_StyleConfig `protobuf:"bytes,2,rep,name=style_config,json=styleConfig,proto3" json:"style_config,omitempty"`
	TokenP2              string                          `protobuf:"bytes,30,opt,name=token_p2,json=tokenP2,proto3" json:"token_p2,omitempty"`
	CacheBaseUrl         string                          `protobuf:"bytes,31,opt,name=cache_base_url,json=cacheBaseUrl,proto3" json:"cache_base_url,omitempty"`
	CacheFile            []*ResourceManifest_CacheFile   `protobuf:"bytes,72,rep,name=cache_file,json=cacheFile,proto3" json:"cache_file,omitempty"`
	CacheFile_2          []string                        `protobuf:"bytes,9,rep,name=cache_file_2,json=cacheFile2,proto3" json:"cache_file_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ResourceManifest) Reset()         { *m = ResourceManifest{} }
func (m *ResourceManifest) String() string { return proto.CompactTextString(m) }
func (*ResourceManifest) ProtoMessage()    {}
func (*ResourceManifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d561545c06fb5527, []int{0}
}

func (m *ResourceManifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceManifest.Unmarshal(m, b)
}
func (m *ResourceManifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceManifest.Marshal(b, m, deterministic)
}
func (m *ResourceManifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceManifest.Merge(m, src)
}
func (m *ResourceManifest) XXX_Size() int {
	return xxx_messageInfo_ResourceManifest.Size(m)
}
func (m *ResourceManifest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceManifest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceManifest proto.InternalMessageInfo

func (m *ResourceManifest) GetStyleConfig() []*ResourceManifest_StyleConfig {
	if m != nil {
		return m.StyleConfig
	}
	return nil
}

func (m *ResourceManifest) GetTokenP2() string {
	if m != nil {
		return m.TokenP2
	}
	return ""
}

func (m *ResourceManifest) GetCacheBaseUrl() string {
	if m != nil {
		return m.CacheBaseUrl
	}
	return ""
}

func (m *ResourceManifest) GetCacheFile() []*ResourceManifest_CacheFile {
	if m != nil {
		return m.CacheFile
	}
	return nil
}

func (m *ResourceManifest) GetCacheFile_2() []string {
	if m != nil {
		return m.CacheFile_2
	}
	return nil
}

type ResourceManifest_CacheFile struct {
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceManifest_CacheFile) Reset()         { *m = ResourceManifest_CacheFile{} }
func (m *ResourceManifest_CacheFile) String() string { return proto.CompactTextString(m) }
func (*ResourceManifest_CacheFile) ProtoMessage()    {}
func (*ResourceManifest_CacheFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d561545c06fb5527, []int{0, 0}
}

func (m *ResourceManifest_CacheFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceManifest_CacheFile.Unmarshal(m, b)
}
func (m *ResourceManifest_CacheFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceManifest_CacheFile.Marshal(b, m, deterministic)
}
func (m *ResourceManifest_CacheFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceManifest_CacheFile.Merge(m, src)
}
func (m *ResourceManifest_CacheFile) XXX_Size() int {
	return xxx_messageInfo_ResourceManifest_CacheFile.Size(m)
}
func (m *ResourceManifest_CacheFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceManifest_CacheFile.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceManifest_CacheFile proto.InternalMessageInfo

func (m *ResourceManifest_CacheFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type ResourceManifest_StyleConfig struct {
	UrlPrefix_1          string                               `protobuf:"bytes,1,opt,name=url_prefix_1,json=urlPrefix1,proto3" json:"url_prefix_1,omitempty"`
	UrlPrefix_2          string                               `protobuf:"bytes,9,opt,name=url_prefix_2,json=urlPrefix2,proto3" json:"url_prefix_2,omitempty"`
	StyleId              ResourceManifest_StyleConfig_StyleID `protobuf:"varint,3,opt,name=style_id,json=styleId,proto3,enum=mps.ResourceManifest_StyleConfig_StyleID" json:"style_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ResourceManifest_StyleConfig) Reset()         { *m = ResourceManifest_StyleConfig{} }
func (m *ResourceManifest_StyleConfig) String() string { return proto.CompactTextString(m) }
func (*ResourceManifest_StyleConfig) ProtoMessage()    {}
func (*ResourceManifest_StyleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d561545c06fb5527, []int{0, 1}
}

func (m *ResourceManifest_StyleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceManifest_StyleConfig.Unmarshal(m, b)
}
func (m *ResourceManifest_StyleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceManifest_StyleConfig.Marshal(b, m, deterministic)
}
func (m *ResourceManifest_StyleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceManifest_StyleConfig.Merge(m, src)
}
func (m *ResourceManifest_StyleConfig) XXX_Size() int {
	return xxx_messageInfo_ResourceManifest_StyleConfig.Size(m)
}
func (m *ResourceManifest_StyleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceManifest_StyleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceManifest_StyleConfig proto.InternalMessageInfo

func (m *ResourceManifest_StyleConfig) GetUrlPrefix_1() string {
	if m != nil {
		return m.UrlPrefix_1
	}
	return ""
}

func (m *ResourceManifest_StyleConfig) GetUrlPrefix_2() string {
	if m != nil {
		return m.UrlPrefix_2
	}
	return ""
}

func (m *ResourceManifest_StyleConfig) GetStyleId() ResourceManifest_StyleConfig_StyleID {
	if m != nil {
		return m.StyleId
	}
	return ResourceManifest_StyleConfig__
}

func init() {
	proto.RegisterEnum("mps.ResourceManifest_StyleConfig_StyleID", ResourceManifest_StyleConfig_StyleID_name, ResourceManifest_StyleConfig_StyleID_value)
	proto.RegisterType((*ResourceManifest)(nil), "mps.ResourceManifest")
	proto.RegisterType((*ResourceManifest_CacheFile)(nil), "mps.ResourceManifest.CacheFile")
	proto.RegisterType((*ResourceManifest_StyleConfig)(nil), "mps.ResourceManifest.StyleConfig")
}

func init() { proto.RegisterFile("ResourceManifest.proto", fileDescriptor_d561545c06fb5527) }

var fileDescriptor_d561545c06fb5527 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0xe3, 0x30,
	0x10, 0xc6, 0x37, 0xcd, 0xb6, 0x69, 0xa6, 0x55, 0xd7, 0xeb, 0xc3, 0xca, 0x5b, 0x24, 0x1a, 0x2a,
	0x0e, 0xe1, 0x52, 0xa9, 0x2e, 0x67, 0x0e, 0x24, 0x02, 0x7a, 0x08, 0xaa, 0x02, 0x9c, 0xad, 0x34,
	0x75, 0x20, 0xc2, 0xf9, 0x23, 0x3b, 0x91, 0xe0, 0x0d, 0x78, 0x4c, 0x1e, 0x05, 0xc5, 0xa5, 0x2d,
	0x14, 0x24, 0x6e, 0x33, 0x9f, 0x7f, 0xdf, 0xf8, 0xf3, 0xc8, 0xf0, 0x2f, 0xe4, 0xaa, 0xa8, 0x65,
	0xcc, 0x83, 0x28, 0x4f, 0x13, 0xae, 0xaa, 0x49, 0x29, 0x8b, 0xaa, 0xc0, 0x66, 0x56, 0xaa, 0xf1,
	0xcb, 0x6f, 0x40, 0xfb, 0xe7, 0xd8, 0x87, 0xbe, 0xaa, 0x9e, 0x05, 0x67, 0x71, 0x91, 0x27, 0xe9,
	0x3d, 0x69, 0x39, 0xa6, 0xdb, 0xa3, 0x47, 0x93, 0xac, 0x54, 0x93, 0x2f, 0xc3, 0x6e, 0x1a, 0xd2,
	0xd3, 0x60, 0xd8, 0x53, 0xbb, 0x06, 0xff, 0x87, 0x6e, 0x55, 0x3c, 0xf2, 0x9c, 0x95, 0x94, 0x1c,
	0x3a, 0x86, 0x6b, 0x87, 0x96, 0xee, 0x17, 0x14, 0x1f, 0xc3, 0x20, 0x8e, 0xe2, 0x07, 0xce, 0x96,
	0x91, 0xe2, 0xac, 0x96, 0x82, 0x8c, 0x34, 0xd0, 0xd7, 0xea, 0x79, 0xa4, 0xf8, 0x9d, 0x14, 0xf8,
	0x0c, 0x60, 0x4d, 0x25, 0xa9, 0xe0, 0xe4, 0x4a, 0x87, 0x18, 0x7d, 0x1f, 0xc2, 0x6b, 0xb8, 0x8b,
	0x54, 0xf0, 0xd0, 0x8e, 0x37, 0x25, 0x76, 0xa0, 0xbf, 0xf3, 0x33, 0x4a, 0x6c, 0xc7, 0x74, 0xed,
	0x10, 0xb6, 0x00, 0x1d, 0xba, 0x60, 0x6f, 0x9d, 0xf8, 0x00, 0x6c, 0x0d, 0xe6, 0x51, 0xc6, 0x49,
	0x4b, 0xe7, 0xe9, 0x36, 0xc2, 0x75, 0x94, 0xf1, 0xe1, 0xab, 0x01, 0xbd, 0x0f, 0x2f, 0x6d, 0x66,
	0xd7, 0x52, 0xb0, 0x52, 0xf2, 0x24, 0x7d, 0x62, 0x53, 0x62, 0x68, 0x1e, 0x6a, 0x29, 0x16, 0x5a,
	0x9a, 0xee, 0x11, 0xcd, 0xed, 0x9f, 0x09, 0x8a, 0x7d, 0xe8, 0xae, 0xd7, 0x9c, 0xae, 0x88, 0xe9,
	0x18, 0xee, 0x80, 0x9e, 0xfc, 0xb8, 0xe2, 0x75, 0x3d, 0xf7, 0x43, 0x4b, 0x5b, 0xe7, 0xab, 0xf1,
	0x25, 0x58, 0xef, 0x1a, 0x6e, 0x83, 0xc1, 0xd0, 0x2f, 0x0c, 0xd0, 0xf1, 0x66, 0x41, 0xc0, 0xa6,
	0x68, 0x80, 0x2d, 0x30, 0xbd, 0x59, 0x80, 0xfe, 0x60, 0x1b, 0xda, 0xfe, 0x6d, 0xa3, 0xa1, 0x4d,
	0x49, 0xd1, 0xdf, 0x2d, 0x4a, 0xd1, 0xe9, 0xb2, 0xa3, 0xbf, 0xc5, 0xec, 0x2d, 0x00, 0x00, 0xff,
	0xff, 0xcb, 0x6d, 0x74, 0x0e, 0x30, 0x02, 0x00, 0x00,
}
